name: Create UDE (OIDC, no secrets)
 
on:
  workflow_dispatch:
 
permissions:
id-token: write   # required for GitHub OIDC
contents: read
 
jobs:
create-ude:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v4
 
# Install PAC CLI wrapper actions
- uses: microsoft/powerplatform-actions/actions-install@v1.9.1
 
# Create environment using federated credentials (no client secret)
- name: Create UDE environment
uses: microsoft/powerplatform-actions/create-environment@v1.9.1
with:
# OIDC: only app-id + tenant-id required when federated credentials are configured
app-id:    ${{ secrets.PP_CLIENT_ID }}
tenant-id: ${{ secrets.PP_TENANT_ID }}
 
# REQUIRED display name for the new environment
name: test-ude-dev01
 
# Environment configuration
environment-type: Sandbox
region: unitedstates        # change if needed
currency: USD
language: 1033
domain-name: ude-dev01
 
# UDE bootstrap (FinOps provisioning anchor)
templates: D365_FinOps_Finance
template-metadata-json: |
{
"PostProvisioningPackages": [
{
"applicationUniqueName": "msdyn_FinanceAndOperationsProvisioningAppAnchor",
"parameters": "DevToolsEnabled=true|DemoDataEnabled=true"
}
]
}
 
